import type { Metadata } from "next";
import React, { ReactNode } from "react";
import "./globals.css";
import Header from "@/components/HeaderUsage";
import Footer from "@/components/FooterUsage";

export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

interface RootLayoutProps {
  children: ReactNode;
}

const RootLayout: React.FC<RootLayoutProps> = ({ children }) => {
  return (
    <html lang="en">
      <head>
        <title>ZomeDex App</title>
      </head>
      <body>
        <header>
          <Header />
        </header>
        <main>{children}</main>
        <footer>
          <Footer/>
        </footer>
      </body>
    </html>
  );
};

export default RootLayout;
